server:
  port: 10000

#log4jdbc
#log4jdbc:
#  spylogdelegator:
#    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelgator

#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug